### ISSUE TITLE
Vendor prefixes?

### ISSUE THREAD

**Issue by rafapaulin** [y0ssar1an/CSS3#65]
Will this syntax support vendor prefixes?

Thanks!

**Comment by variadico** [comment]
By vendor tags, do you mean vendor prefixes?
https://developer.mozilla.org/en-US/docs/Glossary/Vendor_Prefix

**Comment by rafapaulin** [comment]
Yes, sorry!

**Comment by y0ssar1an** [comment]
Are you asking about vendor prefixes like `-webkit-` and `-moz-`? If so, there are already several that are supported. The lists of `-moz-` and `-ms-` prefixed elements are fairly comprehensive. There are lots of missing `-webkit-` prefixed elements because I couldn't find any authoritative lists of them. If you're aware any such lists, please let me know. If there's some commonly used vendor-prefixed elements that you think are missing, please list them here and I'll investigate.

My criteria for including vendor-prefixed stuff is that it must be on the standards track. In other words, it must be described in a W3C spec. That excludes a lot of browser-specific prefixes.

I should point out that a lot of the vendor-prefixes people _think_ they need are actually totally unnecessary, unless they have to support truly ancient browsers. Those prefixed elements have been intentionally left out.

**Comment by rafapaulin** [comment]
Could you, please, provide a example of vendor prefix that your syntax recognize? I am working on a theme of my own, and I could not find the proper scope to any of [-webkit-, -moz-, -o-, -ms-] I tried

**Comment by rafapaulin** [comment]
please?

**Comment by variadico** [comment]
```css
html {
    -ms-text-size-adjust: 100%;
    -webkit-text-size-adjust: 100%;
    -webkit-appearance: none;
}
```

Found these from normalize.css.

**Comment by y0ssar1an** [comment]
I didn't make a separate scope for the vendor prefix. I just included the prefix with the property name, @-rule, etc.

```yaml
# CSS Basic User Interface Module Level 4
property-appearance:
  - match: ((?:-webkit-|-moz-)?\bappearance)\s*(:)
    captures:
      1: support.type.property-name.css
      2: punctuation.separator.key-value.css
```
https://github.com/y0ssar1an/CSS3/blob/develop/CSS3.sublime-syntax#L3609

Does this create any problems for you as a theme maker? If so, I could update the plugin to add a scope to just the `-webkit-`, `-moz-`, and `-ms-` parts.
